version: '3'
services:
  postgresql:
    container_name: postgresql
    image: postgres:12.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=easypassword
    deploy: 
      mode: replicated
      replicas: 1

  mongodb:
    container_name: mongodb
    image: mongo:4.2.5
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=easypassword
      - MONGO_INITDB_DATABASE=mymongodb jdbc:postgresql://postgresql-database:5432/postgres

    deploy: 
      mode: replicated
      replicas: 1

  grafana:
    container_name: grafana 
    image: 272952936633.dkr.ecr.us-east-1.amazonaws.com/chat-repo:grafana
    ports:
      - "3000:3000"
    links:
      - prometheus-metrics
    deploy: 
      mode: replicated
      replicas: 1

  prometheus:
    container_name: prometheus
    image: 272952936633.dkr.ecr.us-east-1.amazonaws.com/chat-repo:prometheus
    ports:
      - "9090:9090"
    links: 
      - backend-api
    deploy: 
      mode: replicated
      replicas: 1

  rabbitmq:
    container_name: rabbitmq
    build: rabbitmq
    image: 272952936633.dkr.ecr.us-east-1.amazonaws.com/chat-repo:rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    deploy: 
      mode: replicated
      replicas: 1

  encryption:
    container_name: encryption
    image: 272952936633.dkr.ecr.us-east-1.amazonaws.com/chat-repo:encryption
    ports:
      - "7799:7799"
    deploy: 
      mode: replicated
      replicas: 1

  backend:
    container_name: backend
    image: 272952936633.dkr.ecr.us-east-1.amazonaws.com/chat-repo:backend-api
    ports:
      - "7070:7070"
      - "8080:8080"
    links:
      - rabbitmq
      - encryption
      - postgresql
      - mongodb
    deploy: 
      mode: replicated
      replicas: 1
      placement: 
        constraints:
          - "node.role==manager"
      restart_policy:
        condition: none
        delay: 1s
        max_attempts: 5
        window: 1s
