{
 "title": "Chat",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Mensajes y ficheros enviados",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "MSG" }
   ],
   "targets": [
    {
     "expr": "sum by (application) (increase(message_sent_total [1h]))",
     "legendFormat": "Total mensajes y ficheros enviados"
    },
    {
     "expr": "sum by (application) (increase(message_sent_total {type=\"msgG\"} [1h]))",
     "legendFormat": "Mensajes enviados a grupos"
    },
    {
     "expr": "sum by (application) (increase(message_sent_total {type=\"msgU\"} [1h]))",
     "legendFormat": "Mensajes enviados a usuarios"
    },
    {
     "expr": "sum by (application) (increase(message_sent_total {type=\"fileU\"} [1h]))",
     "legendFormat": "Ficheros enviados a usuarios"
    },
    {
     "expr": "sum by (application) (increase(message_sent_total {type=\"fileG\"} [1h]))",
     "legendFormat": "Ficheros enviados a grupos"
    }
   ]
  },
  {
   "title": "Usuarios creados",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "user" }
   ]
  },
  {
   "title": "Usuarios creados",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "user" }
   ]
  },
  {
   "title": "Publishers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "user" }
   ]
  },
  {
   "title": "Mensajes enviados por sem.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (increase (message_sent_total {type=~\"msgG|msgU\"} [7d]))"
    }
   ]
  },
  {
   "title": "Mensajes y ficheros enviados por sem.",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (increase (message_sent_total [7d]))"
    }
   ]
  },
  {
   "title": "Ficheros enviados por sem.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (increase (message_sent_total {type=~\"fileG|fileU\"} [7d]))"
    }
   ]
  }
 ]
}