{
 "title": "Chat",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Mensajes y ficheros enviados",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "MSG" }
   ],
   "targets": [
    {
     "expr": "sum by (application) (increase(message_sent_total [1h]))",
     "legendFormat": "Total mensajes y ficheros enviados"
    },
    {
     "expr": "sum by (application) (increase(message_sent_total {type=\"msgG\"} [1h]))",
     "legendFormat": "Mensajes enviados a grupos"
    },
    {
     "expr": "sum by (application) (increase(message_sent_total {type=\"msgU\"} [1h]))",
     "legendFormat": "Mensajes enviados a usuarios"
    },
    {
     "expr": "sum by (application) (increase(message_sent_total {type=\"fileU\"} [1h]))",
     "legendFormat": "Ficheros enviados a usuarios"
    },
    {
     "expr": "sum by (application) (increase(message_sent_total {type=\"fileG\"} [1h]))",
     "legendFormat": "Ficheros enviados a grupos"
    }
   ]
  },
  {
   "title": "Contadores",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MSG" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "message_sent_total", "legendFormat": "Mensajes enviados" },
    {
     "expr": "message_sent_total {type=\"msgU\"}",
     "legendFormat": "Mensajes enviados a usuarios"
    },
    {
     "expr": "message_sent_total {type=\"msgG\"}",
     "legendFormat": "Mensajes enviados a grupos"
    }
   ]
  },
  {
   "title": "Publishers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(recv{type=\"user\"})"
    }
   ]
  }
 ]
}