apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/abel/kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: backend-api
  name: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /home/abel/kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: backend-api
    spec:
      containers:
      - image: thechatthatrocksacr.azurecr.io/backend-api:v4
        imagePullPolicy: ""
        name: backend-api
        ports:
        - containerPort: 7070
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
