apiVersion: v1
kind: Service
metadata:
  name: backend-api
spec:
  type: NodePort
  ports:
  - name: "7070"
    port: 7070
    targetPort: 7070
    nodePort: 30082
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30081
  selector:
    io.kompose.service: backend-api
status:
  loadBalancer: {}
