apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/abel/kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: encryption
  name: encryption
spec:
  ports:
  - name: "7799"
    port: 7799
    targetPort: 7799
  selector:
    io.kompose.service: encryption
status:
  loadBalancer: {}
