apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/abel/kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-database
  name: mongodb-database
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    io.kompose.service: mongodb-database
status:
  loadBalancer: {}
