version: '3'
services:
  postgresql-database:
    image: postgres:12.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=easypassword

  mongodb-database:
    image: mongo:4.2.5
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=easypassword
      - MONGO_INITDB_DATABASE=mymongodb

  grafana-dashboard:
    image: grafana/grafana:7.0.0-beta3
    ports:
      - "3000:3000"
    links:
      - prometheus-metrics

  prometheus-metrics:
    image: abelcht/thechatthatrocks:prometheusv1
    ports:
      - "9090:9090"
    links: 
      - backend-api

  rabbitmq-broker:
    image: abelcht/thechatthatrocks:rabbitmqv1
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"

  encryption:
    image: abelcht/thechatthatrocks:encryptionv1
    ports:
      - "7799:7799"

  backend-api:
    image: abelcht/thechatthatrocks:chatv1
    ports:
      - "7070:7070"
      - "8080:8080"
    links:
      - rabbitmq-broker
      - encryption
      - postgresql-database
      - mongodb-database